pipeline {
  options {
    timeout(time: 60, unit: 'MINUTES')
  }

  environment {
    IMAGE_NAME = 'static-ws'
    IMAGE_REL = 'v1r0'
    CONTAINER_NAME = 'container-static-ws'
    TEST_LOCAL_PORT = 8081
  }
  
  triggers {
    cron('0 1 * * 1-5')
  }

  agent { node { label 'master' } }
  
  stages {
    stage('Step 1') {
      echo "Step 1"
      git branch: "master",
        credentialsId: 'YourGithubSshCredentials',
        url: 'https://github.com/yourAccount/cicd-static-website.git'
    }
    stage('Step 2') {
      sh "docker build -t ${IMAGE_NAME}:${IMAGE_REL} -f ../docker/Dockerfile"
      sh "[ -z \"\$(docker ps -a | grep ${CONTAINER_NAME} 2>/dev/null)\" ] || docker rm -f container-static-ws"
      sh "docker run --detach --name ${CONTAINER_NAME} --rm --publish ${TEST_LOCAL_PORT}:80 ${IMAGE_NAME}:${IMAGE_REL}"
    }
    stage('Step 3') {
      steps {
        script {
          final String url = "http://localhost:${TEST_LOCAL_PORT}/index.html"
          final def (String response, int code) =
                            sh(script: "curl -s -w '\\n%{response_code}', returnStdout: true)
                                .trim()
                                .tokenize("\n")

          echo "HTTP response status code: $code"

          if (code == 200) {
            echo response
          }
        }
      }
    }
  }
}
